// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boil

var TableNames = struct {
	UserPasswords string
	UserTokens    string
	Users         string
}{
	UserPasswords: "user_passwords",
	UserTokens:    "user_tokens",
	Users:         "users",
}
