// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/error/error.proto

package error

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCode) Reset()         { *m = ErrorCode{} }
func (m *ErrorCode) String() string { return proto.CompactTextString(m) }
func (*ErrorCode) ProtoMessage()    {}
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_06057359280e3e69, []int{0}
}

func (m *ErrorCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCode.Unmarshal(m, b)
}
func (m *ErrorCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCode.Marshal(b, m, deterministic)
}
func (m *ErrorCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCode.Merge(m, src)
}
func (m *ErrorCode) XXX_Size() int {
	return xxx_messageInfo_ErrorCode.Size(m)
}
func (m *ErrorCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCode.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCode proto.InternalMessageInfo

func (m *ErrorCode) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

type Error struct {
	Error                *Error_ErrorDetail `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_06057359280e3e69, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() *Error_ErrorDetail {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error_ErrorDetail struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Locale               string   `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_ErrorDetail) Reset()         { *m = Error_ErrorDetail{} }
func (m *Error_ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*Error_ErrorDetail) ProtoMessage()    {}
func (*Error_ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_06057359280e3e69, []int{1, 0}
}

func (m *Error_ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_ErrorDetail.Unmarshal(m, b)
}
func (m *Error_ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *Error_ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_ErrorDetail.Merge(m, src)
}
func (m *Error_ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_Error_ErrorDetail.Size(m)
}
func (m *Error_ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_Error_ErrorDetail proto.InternalMessageInfo

func (m *Error_ErrorDetail) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *Error_ErrorDetail) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *Error_ErrorDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorCode)(nil), "v1.ErrorCode")
	proto.RegisterType((*Error)(nil), "v1.Error")
	proto.RegisterType((*Error_ErrorDetail)(nil), "v1.Error.ErrorDetail")
}

func init() { proto.RegisterFile("proto/v1/error/error.proto", fileDescriptor_06057359280e3e69) }

var fileDescriptor_06057359280e3e69 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0xe9, 0x95, 0x7b, 0xa5, 0x73, 0x77, 0x01, 0x25, 0x5c, 0x10, 0xa4, 0x2b, 0x51, 0x9a,
	0x10, 0x7d, 0x03, 0x7f, 0x5e, 0xa0, 0x4b, 0x17, 0x4a, 0x9a, 0x0e, 0x69, 0x21, 0x65, 0x42, 0x12,
	0xfb, 0x24, 0x3e, 0xb0, 0x38, 0xb5, 0xe2, 0xce, 0xcd, 0xc0, 0xf9, 0xbe, 0x03, 0x03, 0x07, 0x4e,
	0x31, 0x51, 0x21, 0xbd, 0x18, 0x8d, 0x29, 0x51, 0x5a, 0xaf, 0x62, 0x28, 0x76, 0x8b, 0x69, 0x6e,
	0xa1, 0x7e, 0xf9, 0x46, 0x4f, 0x34, 0xa0, 0xb8, 0x02, 0x60, 0xff, 0xee, 0x68, 0x40, 0x59, 0x5d,
	0x57, 0x37, 0x75, 0x57, 0xe3, 0xa6, 0x9b, 0xcf, 0x0a, 0xf6, 0x5c, 0x16, 0x77, 0xb0, 0x67, 0xcc,
	0x9d, 0xe3, 0xfd, 0x85, 0x5a, 0x8c, 0x62, 0xb3, 0xde, 0x67, 0x2c, 0x76, 0x0a, 0xdd, 0xda, 0x39,
	0xbd, 0xc1, 0xf1, 0x0f, 0xfd, 0xe7, 0x89, 0xb8, 0x84, 0x43, 0x20, 0x67, 0x03, 0xca, 0x1d, 0xab,
	0x9f, 0x24, 0x24, 0x9c, 0xcf, 0x98, 0xb3, 0xf5, 0x28, 0xcf, 0x58, 0x6c, 0xf1, 0xd1, 0xbc, 0x6a,
	0x3f, 0x95, 0xf1, 0xa3, 0x57, 0x8e, 0x66, 0x3d, 0xe5, 0x92, 0x47, 0xed, 0xa9, 0xf5, 0x29, 0xba,
	0x36, 0xdb, 0x39, 0x06, 0xd4, 0x36, 0x46, 0x1d, 0xfb, 0xdf, 0x15, 0xfa, 0x03, 0x0f, 0xf0, 0xf0,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xdc, 0x94, 0x74, 0x1e, 0x01, 0x00, 0x00,
}
