version: "3.5"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    command: ["mysqld", "--character-set-server", "utf8mb4"]
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    tty: true
    depends_on:
      - db
    command: /bin/sh -c "/usr/bin/wait-for-it -t 60 db:3306 -- /server"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - server
    command: /bin/sh -c "/usr/bin/wait-for-it -t 60 db:3306 -- /client --grpc-server-endpoint=server:9090"