version: "3.5"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    ports:
      - 3306:3306
    command: ["mysqld", "--character-set-server", "utf8mb4"]
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    tty: true
  client:
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - server