pkgname="db"
output="app/domain/db"
add-global-variants=true
add-panic-variants=true

[mysql]
  dbname = "sample"
  host   = "localhost"
  port   = 3306
  user   = "root"
  pass   = "password"
  sslmode= "disable"
  blacklist = ["schema_migrations"]