pkgname="database"
output="app/interfaces/database"
add-global-variants=true
add-panic-variants=true

[mysql]
  dbname = "sample"
  host   = "localhost"
  port   = 3306
  user   = "root"
  pass   = "password"
  sslmode= "false"
  blacklist = ["schema_migrations"]